### PR TITLE
Issue #25 - Don't call reifyRoles on undeclared types

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by mboes** [comment]
Thanks. PR causes issues with GHC 7.4 and 7.6. Might you have a look?

**Comment by mboes** [comment]
https://travis-ci.org/mboes/th-lift/builds/152069335

**Comment by ddssff** [comment]
Yes, I will look at these - the Role type appeared in 7.8 I guess.   However, I'm not sure whether my patch actually makes it possible to build working Lift instances for undeclared types, because of how the Names come out in the code.  This has been a widespread problem in the code I'm working on.  Hopefully I'll figure out whether I'm making a mistake or whether there is a problem in the Lift instance for Name.

**Comment by ddssff** [comment]
The Name issue I mentioned above was a misunderstanding on my part.  So I think this pull request is ok, though I don't fully understand how one would use the [Role] argument.

**Comment by mboes** [comment]
Thanks!

**Pull request merged**
